#!/bin/bash

LOGFILE=/var/log/minerd.log
PIDFILE=/var/run/minerd.pid

case "$1" in
  start)
    /usr/cpuminer/minerd --algo=scrypt --url=stratum+tcp://us2.litecoinpool.org:3333 --userpass=suryadewa.1:1 >> $LOGFILE 2>&1 &
    echo $! > $PIDFILE
    exit 0
    ;;
  stop)
    pkill --pidfile $PIDFILE
    rm $PIDFILE
    ;;
  status)
    if [[ -e $PIDFILE ]]; then
      cat $PIDFILE
    else
      echo "Not running"
      exit 1
    fi
    ;;
  log)
    tail -f $LOGFILE
    ;;
  *)
    echo "Usage: $0 {start|stop|status|log}"
    exit 1
    ;;
esac
